# Generated by Django 3.2.24 on 2024-04-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
